* Features
** Scheduled commands statuses
** DONE Rescheduling
Changing a scheduled command timespec.

Usage examples:
q --reschedule <jobid> <timespec>
q -r <jobid> <timespec>
schedule --reschedule <jobid> <timespec>
schedule -r <jobid> <timespec>

The '--reschedule' option implied --schedule, so the <jobid> is the id of a scheduled job.

** DONE Disabling and enabling scheduled commands
Any scheduled command can be disabled or enabled with the following commands:

*** Disabling a scheduled command:
q --schedule --disable <jobid>
q --schedule -d <jobid>
schedule --disable <jobid>
schedule -d <jobid>

When a scheduled command is disblaed, it must indicate DISABLED in the "NEXT RUN" field when displaying the status (scheduled commands list).

*** Enabling a scheduled command
q --schedule --enable <jobid>
q --schedule -e <jobid>
schedule --enable <jobid>
schedule -e <jobid>

When a scheduled command is enabled, it must indicate a proper schedule time to run in the "NEXT RUN" field.

** DONE Recalculate NEXT RUN on re-enabling commands
** DONE Immediate run command
** DONE Color coding in the terminal
q output:
  - running command: yellow
  - successfuly terminated: green
  - failed commands: red

schedule:
  - disabled: grey
  - sucessful: green
  - running: yellow
  - unsuccessful: red

** GUI
Qt based GUI.

